if status is-interactive
    # Commands to run in interactive sessions can go here
end

alias esp '. /home/pollivie/esp/esp-idf/export.fish'
alias dbg './dbg.sh'
alias egrep 'grep -E --color=auto'
alias fgrep 'grep -F --color=auto'
alias g git
alias gcl 'git clone'
alias ga 'git add'
alias gaa 'git add .'
alias gb 'git branch'
alias gba 'git branch -a'
alias gc 'git commit -v'
alias gca 'git commit -v -a'
alias gcl 'git clone'
alias gcm 'git checkout master'
alias gcmsg 'git commit -m'
alias gco 'git checkout'
alias gcount 'git shortlog -sn'
alias gcp 'git cherry-pick'
alias gl 'git pull'
alias glg 'git log --stat --max-count=5'
alias glgg 'git log --graph --max-count=5'
alias gm 'git merge'
alias gp 'git push'
alias grep 'grep --color=auto'
alias grh 'git reset HEAD'
alias grhh 'git reset HEAD --hard'
alias gss 'git status -s'
alias gst 'git status'
alias gup 'git fetch && git rebase'
alias l. 'ls -d .* --color=auto'
alias la 'eza --all --color --long --header --icons --git'
alias ll 'ls -l --color=auto'
alias ls 'eza --color --long --header --icons --git'
alias lz lazygit
alias pbcopy 'xsel -bi'
alias pbpaste 'xsel -bo'
alias reload 'exec bash'
alias run './run.sh'
alias tree 'eza --all --color --icons --git --tree'
alias xzegrep 'xzegrep --color=auto'
alias xzfgrep 'xzfgrep --color=auto'
alias xzgrep 'xzgrep --color=auto'
alias zb 'zig build'
alias zbc 'zig build check'
alias zbo 'zig build -Doptimize=ReleaseFast'
alias zbor 'zig build -Doptimize=ReleaseFast run'
alias zbr 'zig build run'
alias zbt 'zig build test'
alias zegrep 'zegrep --color=auto'
alias zfgrep 'zfgrep --color=auto'
alias zgrep 'zgrep --color=auto'
alias zr 'zig run *.zig'
alias zt 'zig test *.zig'

# Generated for envman. Do not edit.
test -s ~/.config/envman/load.fish; and source ~/.config/envman/load.fish
